In [3]:
# we are using wget to download the mage directly from the internet
!wget 'https://gratisography.com/wp-content/uploads/2024/10/gratisography-cool-cat-800x525.jpg'

--2024-11-01 07:29:39--  https://gratisography.com/wp-content/uploads/2024/10/gratisography-cool-cat-800x525.jpg
Resolving gratisography.com (gratisography.com)... 104.21.62.193, 172.67.138.170, 2606:4700:3034::ac43:8aaa, ...
Connecting to gratisography.com (gratisography.com)|104.21.62.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/jpeg]
Saving to: ‘gratisography-cool-cat-800x525.jpg’

gratisography-cool-     [   <=>              ]  73.46K   180KB/s    in 0.4s    

2024-11-01 07:29:45 (180 KB/s) - ‘gratisography-cool-cat-800x525.jpg’ saved [75219]



**libraries theat can be used in image processing:**
1. matplotlib.image
2. Pillow
3. OpenCV(cv2)

In [2]:
# importing the image module from matplotlib module 
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

In [3]:
# loading an image though matplotlib.img module 
img = mpimg.imread('/home/kayi/Desktop/ML projects/Image processing for DL/cat.jpg')

In [4]:
# checking how the image has been loaded(type of image)
type(img)

numpy.ndarray

In [5]:
# we can also check the shape of the image 
img.shape
# the first and second value represent the dimension and the third value represents the channel 

(525, 800, 3)

In [6]:
#how the image has been stored as a numpy array
print(img)

[[[39 39 39]
  [36 36 36]
  [42 42 42]
  ...
  [ 3  3  3]
  [ 4  4  4]
  [ 6  6  6]]

 [[27 27 27]
  [27 27 27]
  [37 37 37]
  ...
  [ 4  4  4]
  [ 5  5  5]
  [ 7  7  7]]

 [[27 27 27]
  [29 29 29]
  [34 34 34]
  ...
  [ 5  5  5]
  [ 6  6  6]
  [ 7  7  7]]

 ...

 [[11 11 11]
  [10 10 10]
  [ 8  8  8]
  ...
  [ 6  6  6]
  [ 7  7  7]
  [ 7  7  7]]

 [[12 12 12]
  [10 10 10]
  [ 8  8  8]
  ...
  [ 6  6  6]
  [ 6  6  6]
  [ 7  7  7]]

 [[13 13 13]
  [11 11 11]
  [ 8  8  8]
  ...
  [ 6  6  6]
  [ 6  6  6]
  [ 6  6  6]]]
